### ISSUE TITLE
sineyk yon degistiremiyor

### ISSUE THREAD

**Issue by ademgunesen** [makrofaj67/100daysofcode#1]
Dumduz gidiyor, saga sole donme ozelligi olmasi lazim. Yeni versiyonu dortgozle bekliyoruz

**Comment by makrofaj67** [comment]
ÇAĞLAR BUNU OKUYOSAN TOPSUN XDDDDDD

**Comment by makrofaj67** [comment]
NASI LAFI KOYDUM AMA BU GİBİ BAK

SU İÇERKEN YILAN BİLE DOKUNMAZ
O SIRADA YILAN
BİZE ÖYLE Bİ BİLGİ GELMEDİ :D

**Comment by makrofaj67** [comment]
çözüldü isteklerinizi yeni issuuelarda bekleriz 

                             ___-------___
                         _-~~             ~~-_
                      _-~                    /~-_
   /^\__/^\         /~  \                   /    \
 /|  O|| O|        /      \_______________/        \
| |___||__|      /       /                \          \
|          \    /      /                    \          \
|   (_______) /______/                        \_________ \
|         / /         \                      /            \
 \         \^\\         \                  /               \     /
   \         ||           \______________/      _-_       //\__//
     \       ||------_-~~-_ ------------- \ --/~   ~\    || __/
       ~-----||====/~     |==================|       |/~~~~~
        (_(__/  ./     /                    \_\      \.
               (_(___/                         \_____)_)

**Comment by makrofaj67** [comment]
çözüldü yeni sorunlarınnızı yeni issuelarda bekliyoruz 

`                             ___-------___
                         _-~~             ~~-_
                      _-~                    /~-_
   /^\__/^\         /~  \                   /    \
 /|  O|| O|        /      \_______________/        \
| |___||__|      /       /                \          \
|          \    /      /                    \          \
|   (_______) /______/                        \_________ \
|         / /         \                      /            \
 \         \^\\         \                  /               \     /
   \         ||           \______________/      _-_       //\__//
     \       ||------_-~~-_ ------------- \ --/~   ~\    || __/
       ~-----||====/~     |==================|       |/~~~~~
        (_(__/  ./     /                    \_\      \.
               (_(___/                         \_____)_)`
